# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddd7df2fd572f203cfa201e8c9b3215ea159f4a8af2c2ed2ada2be50c13bde58764d4e453362fc288fd71d4e49b42124fd546bc1b70408f1bd47a1b8c4bd5616

test:
  secret_key_base: 856e76d369a2cf0ada97917c592bf759c98d38a1f26b492561771a95d10cea1a374737e4001190056e972a6363c8c1409d59ec3f5ecf32a01223682d374f1993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
